config/routes.rb
Rails.application.routes.draw do
  root 'main#entrance'
  
  get 'main/entrance'
  
  resources :lightfoods
  
  resources :heavyfoods
  
  resources :takeoutfoods

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/heavyfood.rb
class Heavyfood < ApplicationRecord
    validates :title,
    presence: true,
    length: { minimum: 3 }
end

app/models/lightfood.rb
class Lightfood < ApplicationRecord
    validates :title,
    presence: true,
    length: { minimum: 3 }
end

app/models/takeoutfood.rb
class Takeoutfood < ApplicationRecord
    validates :title,
    presence: true,
    length: { minimum: 3 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/heavyfoods_controller.rb
class HeavyfoodsController < ApplicationController
    def new
        @heavyfood = Heavyfood.new
    end
    def create
        @heavyfood = Heavyfood.new(heavyfood_params)
        
        if @heavyfood.save
            redirect_to @heavyfood
        else
            render 'new'
        end
    end
    def show
       @heavyfood = Heavyfood.find(params[:id])
    end
    def index
       @heavyfoods = Heavyfood.all 
    end
    def edit
        @heavyfood = Heavyfood.find(params[:id])
    end
    def update
        @heavyfood = Heavyfood.find(params[:id])
        if @heavyfood.update(heavyfood_params)
        redirect_to @heavyfood
        else
        render 'edit'
        end
    end
    def destroy
        @heavyfood = Heavyfood.find(params[:id])
        @heavyfood.destroy
        redirect_to heavyfoods_path
    end
    private
        def heavyfood_params
           params.require(:heavyfood).permit(:title, :address, :text, :imagelink, :webpage) 
        end
end

app/controllers/lightfoods_controller.rb
class LightfoodsController < ApplicationController
    def new
        @lightfood = Lightfood.new
    end
    def create
        @lightfood = Lightfood.new(lightfood_params)
        
        if @lightfood.save
            redirect_to @lightfood
        else
            render 'new'
        end
    end
    def show
       @lightfood = Lightfood.find(params[:id])
    end
    def index
       @lightfoods = Lightfood.all 
    end
    def edit
        @lightfood = Lightfood.find(params[:id])
    end
    def update
        @lightfood = Lightfood.find(params[:id])
        if @lightfood.update(lightfood_params)
        redirect_to @lightfood
        else
        render 'edit'
        end
    end
    def destroy
        @lightfood = Lightfood.find(params[:id])
        @lightfood.destroy
        redirect_to lightfoods_path
    end
    private
        def lightfood_params
           params.require(:lightfood).permit(:title, :address, :text, :imagelink, :webpage) 
        end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def entrance
  end
end

app/controllers/takeoutfoods_controller.rb
class TakeoutfoodsController < ApplicationController
    def new
        @takeoutfood = Takeoutfood.new
    end
    def create
        @takeoutfood = Takeoutfood.new(takeoutfood_params)
        
        if @takeoutfood.save
            redirect_to @takeoutfood
        else
            render 'new'
        end
    end
    def show
       @takeoutfood = Takeoutfood.find(params[:id])
    end
    def index
       @takeoutfoods = Takeoutfood.all 
    end
    def edit
        @takeoutfood = Takeoutfood.find(params[:id])
    end
    def update
        @takeoutfood = Takeoutfood.find(params[:id])
        if @takeoutfood.update(takeoutfood_params)
        redirect_to @takeoutfood
        else
        render 'edit'
        end
    end
    def destroy
        @takeoutfood = Takeoutfood.find(params[:id])
        @takeoutfood.destroy
        redirect_to takeoutfoods_path
    end
    private
        def takeoutfood_params
           params.require(:takeoutfood).permit(:title, :address, :text, :imagelink, :webpage) 
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fooda_helper.rb
module FoodaHelper
end

app/helpers/foodb_helper.rb
module FoodbHelper
end

app/helpers/foodc_helper.rb
module FoodcHelper
end

app/helpers/heavyfoods_helper.rb
module HeavyfoodsHelper
end

app/helpers/lightfoods_helper.rb
module LightfoodsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/takeoutfoods_helper.rb
module TakeoutfoodsHelper
end

app/views/heavyfoods/_form.html.erb
<%= form_for @heavyfood do |f| %>
<p>
<%= f.label :title %><br>
<%= f.text_field :title %>
</p>
<p>
<%= f.label :address %><br>
<%= f.text_field :address %>
</p>
<p>
<%= f.label :text %><br>
<%= f.text_area :text %>
</p>
<p>
<%= f.label :imagelink %><br>
<%= f.text_field :imagelink %>
</p>
<p>
<%= f.label :webpage %><br>
<%= f.text_field :webpage %>
</p>
<p>
<%= f.submit %>
</p>
<% end %>

<% if @heavyfood.errors.any? %>
<div id="error_explanation">
<h2>
<%= pluralize(@heavyfood.errors.count, "error") %> prohibited
this article from being saved:
</h2>
<ul>
<% @heavyfood.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
</div>
<% end %>

app/views/heavyfoods/edit.html.erb
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag "oppanGwanakStyle.css" %>
    <title>관악구 맛집 백과 - 무거운 식당</title>
</head>

<body>
    <div class="container-sm card mt-5 p-3 text-center">
<h1 class="mb-3">수정하기</h1>
<%= render 'form' %>

<div class="container">
<div class="btn btn-warning p-0">
  <%= link_to '돌아가기', heavyfoods_path, :class => "btn" %>
</div>
</div>
</div>
</body>

app/views/heavyfoods/index.html.erb
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag "oppanGwanakStyle.css" %>
    <title>관악구 맛집 백과 - 무거운 식당</title>
</head>

<body>
    <nav class="navbar navbar-expand-sm navbar-light">
        <div class="container-lg outsidenav">
            <a class="navbar-brand" href="/">관악구 맛집 백과</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapsible navbar-collapse" id="collapsibleNavbar">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="/lightfoods">가벼운 식당</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="/heavyfoods">무거운 식당</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/takeoutfoods">배달/포장</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <main>

        <div class="container-lg">
            <div class="page-header text-center p-4 mb-3 rounded">
                <h1 class="titlehead display-4 mb-2">무거운 식당</h1>
                <p class="lead mb-0">사진을 누르시면 더 자세한 정보를 확인할 수 있습니다.</p>
            </div>

            <% @heavyfoods.each do |heavyfood| %>
            <div class="card mb-3">
                <div class="card-body text-center text-sm-left border border-warning shadow">
                    <div class="row">
                        <div class="col-lg-8 col-sm-7">
                            <h1><%= heavyfood.title %></h1>
                            <p class="lead"><%= heavyfood.address %></p>
                            <p class="description"><%= heavyfood.text %></p>
                            <p>
                            <span class="btn btn-warning p-0"><%= link_to '수정하기', edit_heavyfood_path(heavyfood), :class => "btn" %></span>
                            <span class="btn btn-warning p-0"><%= link_to '삭제하기', heavyfood_path(heavyfood), method: :delete, data: { confirm: '정말 삭제하시겠습니까?' }, :class => "btn" %></span>
                            </p>
                        </div>
                        <div class="col-lg-4 col-sm-5 align-items-center d-flex">
                            <a href="<%= heavyfood.webpage %>" target="_blank"><img
                                    src="<%= heavyfood.imagelink %>" alt="<%= heavyfood.title %>"
                                    class="img-fluid border rounded border-muted"></a>
                        </div>
                    </div>
                </div>
            </div>
            <% end %>
        
            <div class="text-center">
            <a class="btn btn-warning mb-3" href="/heavyfoods/new" role="button">새 식당 추가</a>
            </div>

        </div>
    </main>

    <footer class="footer">
        <div class="container-md pl-3 pr-3">
            <p class="text-secondary mt-2 mb-1">본 페이지는 송상록(2019-12213, 심리학과)의 웹프로그래밍개론 수업 실습용 페이지입니다.</p>
            <p class="text-muted mb-1">식당 사진은 송상록 본인이 촬영했습니다.</p>
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"
        integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous">
    </script>
</body>

</html>

app/views/heavyfoods/new.html.erb
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag "oppanGwanakStyle.css" %>
    <title>관악구 맛집 백과 - 무거운 식당</title>
</head>

<body>
<div class="container-sm card mt-5 p-3 text-center">
<h1 class="mb-3">새로운 식당</h1>
<%= render 'form' %>

<div class="container">
<div class="btn btn-warning">
  <%= link_to '돌아가기', heavyfoods_path, :class => "btn" %>
</div>
</div>
</div>
</body>

app/views/heavyfoods/show.html.erb
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag "oppanGwanakStyle.css" %>
    <title>관악구 맛집 백과 - 가벼운 식당</title>
</head>

<body>
    <div class="container-sm card mt-5 p-3 text-center center-screen">
<h1 class="mb-3">식당이 잘 저장되었습니다. 확인해보세요!</h1>
<div class="container">
<div class="btn btn-warning p-0">
  <%= link_to '돌아가기', heavyfoods_path, :class => "btn" %>
</div>
</div>
</div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lightfoods/_form.html.erb
<%= form_for @lightfood do |f| %>
<p>
<%= f.label :title %><br>
<%= f.text_field :title %>
</p>
<p>
<%= f.label :address %><br>
<%= f.text_field :address %>
</p>
<p>
<%= f.label :text %><br>
<%= f.text_area :text %>
</p>
<p>
<%= f.label :imagelink %><br>
<%= f.text_field :imagelink %>
</p>
<p>
<%= f.label :webpage %><br>
<%= f.text_field :webpage %>
</p>
<p>
<%= f.submit %>
</p>
<% end %>

<% if @lightfood.errors.any? %>
<div id="error_explanation">
<h2>
<%= pluralize(@lightfood.errors.count, "error") %> prohibited
this article from being saved:
</h2>
<ul>
<% @lightfood.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
</div>
<% end %>

app/views/lightfoods/edit.html.erb
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag "oppanGwanakStyle.css" %>
    <title>관악구 맛집 백과 - 가벼운 식당</title>
</head>

<body>
<div class="container-sm card mt-5 p-3 text-center">
<h1 class="mb-3">수정하기</h1>
<%= render 'form' %>

<div class="container">
<div class="btn btn-warning p-0">
  <%= link_to '돌아가기', lightfoods_path, :class => "btn" %>
</div>
</div>
</div>
</body>

app/views/lightfoods/index.html.erb
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag "oppanGwanakStyle.css" %>
    <title>관악구 맛집 백과 - 가벼운 식당</title>
</head>

<body>
    <nav class="navbar navbar-expand-sm navbar-light">
        <div class="container-lg outsidenav">
            <a class="navbar-brand" href="/">관악구 맛집 백과</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapsible navbar-collapse" id="collapsibleNavbar">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" href="/lightfoods">가벼운 식당</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/heavyfoods">무거운 식당</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/takeoutfoods">배달/포장</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <main>
        <div class="container-lg">
            <div class="page-header text-center p-4 mb-3 text-dark rounded">
                <h1 class="titlehead display-4 mb-2">가벼운 식당</h1>
                <p class="lead mb-0">사진을 누르시면 더 자세한 정보를 확인할 수 있습니다.</p>
            </div>

           <% @lightfoods.each do |lightfood| %>
            <div class="card mb-3">
                <div class="card-body text-center text-sm-left border border-warning shadow">
                    <div class="row">
                        <div class="col-lg-8 col-sm-7">
                            <h1><%= lightfood.title %></h1>
                            <p class="lead"><%= lightfood.address %></p>
                            <p class="description"><%= lightfood.text %></p>
                            <p>
                            <span class="btn btn-warning p-0"><%= link_to '수정하기', edit_lightfood_path(lightfood), :class => "btn" %></span>
                            <span class="btn btn-warning p-0"><%= link_to '삭제하기', lightfood_path(lightfood), method: :delete, data: { confirm: '정말 삭제하시겠습니까?' }, :class => "btn" %></span>
                            </p>
                        </div>
                        <div class="col-lg-4 col-sm-5 align-items-center d-flex">
                            <a href="<%= lightfood.webpage %>" target="_blank"><img
                                    src="<%= lightfood.imagelink %>" alt="<%= lightfood.title %>"
                                    class="img-fluid border rounded border-muted"></a>
                        </div>
                    </div>
                </div>
            </div>
            <% end %>
            
            <div class="text-center">
            <a class="btn btn-warning mb-3" href="/lightfoods/new" role="button">새 식당 추가</a>
            </div>

        </div>
    </main>

    <footer class="footer">
        <div class="container-md pl-3 pr-3">
            <p class="text-muted mt-2 mb-1">본 페이지는 송상록(2019-12213, 심리학과)의 웹프로그래밍개론 수업 실습용 페이지입니다.</p>
            <p class="text-muted mb-1">식당 사진은 송상록 본인이 촬영했습니다.</p>
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
    </script>
</body>

</html>

app/views/lightfoods/new.html.erb
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag "oppanGwanakStyle.css" %>
    <title>관악구 맛집 백과 - 가벼운 식당</title>
</head>

<body>

<div class="container-sm card mt-5 p-3 text-center">
<h1 class="mb-3">새로운 식당</h1>
<%= render 'form' %>

<div class="container">
<div class="btn btn-warning">
  <%= link_to '돌아가기', lightfoods_path, :class => "btn" %>
</div>
</div>
</div>
</body>

app/views/lightfoods/show.html.erb
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag "oppanGwanakStyle.css" %>
    <title>관악구 맛집 백과 - 가벼운 식당</title>
</head>

<body>
    <div class="container-sm card mt-5 p-3 text-center center-screen">
<h1 class="mb-3">식당이 잘 저장되었습니다. 확인해보세요!</h1>
<div class="container">
<div class="btn btn-warning p-0">
  <%= link_to '돌아가기', lightfoods_path, :class => "btn" %>
</div>
</div>
</div>
</body>

app/views/takeoutfoods/_form.html.erb
<%= form_for @takeoutfood do |f| %>
<p>
<%= f.label :title %><br>
<%= f.text_field :title %>
</p>
<p>
<%= f.label :address %><br>
<%= f.text_field :address %>
</p>
<p>
<%= f.label :text %><br>
<%= f.text_area :text %>
</p>
<p>
<%= f.label :imagelink %><br>
<%= f.text_field :imagelink %>
</p>
<p>
<%= f.label :webpage %><br>
<%= f.text_field :webpage %>
</p>
<p>
<%= f.submit %>
</p>
<% end %>

<% if @takeoutfood.errors.any? %>
<div id="error_explanation">
<h2>
<%= pluralize(@takeoutfood.errors.count, "error") %> prohibited
this article from being saved:
</h2>
<ul>
<% @takeoutfood.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
</div>
<% end %>

app/views/takeoutfoods/index.html.erb
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag "oppanGwanakStyle.css" %>
    <title>관악구 맛집 백과 - 배달/포장</title>
</head>

<body>
    <nav class="navbar navbar-expand-sm navbar-light">
        <div class="container-lg outsidenav">
            <a class="navbar-brand" href="/">관악구 맛집 백과</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapsible navbar-collapse" id="collapsibleNavbar">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="/lightfoods">가벼운 식당</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/heavyfoods">무거운 식당</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="/takeoutfoods">배달/포장</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <main>
        <div class="container-lg">
            <div class="page-header text-center p-4 mb-3 text-dark-50 rounded">
                <h1 class="titlehead display-4 mb-2">배달/포장</h1>
                <p class="lead mb-0">사진을 누르시면 더 자세한 정보를 확인할 수 있습니다.</p>
            </div>

            <% @takeoutfoods.each do |takeoutfood| %>
            <div class="card mb-3">
                <div class="card-body text-center text-sm-left border border-warning shadow">
                    <div class="row">
                        <div class="col-lg-8 col-sm-7">
                            <h1><%= takeoutfood.title %></h1>
                            <p class="lead"><%= takeoutfood.address %></p>
                            <p class="description"><%= takeoutfood.text %></p>
                            <p>
                            <span class="btn btn-warning p-0"><%= link_to '수정하기', edit_takeoutfood_path(takeoutfood), :class => "btn" %></span>
                            <span class="btn btn-warning p-0"><%= link_to '삭제하기', takeoutfood_path(takeoutfood), method: :delete, data: { confirm: '정말 삭제하시겠습니까?' }, :class => "btn" %></span>
                            </p>
                        </div>
                        <div class="col-lg-4 col-sm-5 align-items-center d-flex">
                            <a href="<%= takeoutfood.webpage %>" target="_blank"><img
                                    src="<%= takeoutfood.imagelink %>" alt="<%= takeoutfood.title %>"
                                    class="img-fluid border rounded border-muted"></a>
                        </div>
                    </div>
                </div>
            </div>
            <% end %>
            
            <div class="text-center">
            <a class="btn btn-warning mb-3" href="/takeoutfoods/new" role="button">새 식당 추가</a>
            </div>
        </div>
    </main>


    <footer class="footer">
        <div class="container-md">
            <p class="text-muted mt-2 mb-1">본 페이지는 송상록(2019-12213, 심리학과)의 웹프로그래밍개론 수업 실습용 페이지입니다.</p>
            <p class="text-muted mb-1">식당 사진은 송상록 본인이 촬영했습니다.</p>
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
    </script>
</body>

</html>